#Demo Spring application

trigger:
 branches:
    include:
      - master
pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'BuildArtifact'
    displayName: ' Building Artifact'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'Building Artifact'
        steps:
        - template: 'cicd/templates/build.yml'

  - stage: 'Dockerize'
    displayName: 'Create Docker Image'
    condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'))
    jobs:
      - job: 'CreateDockerImage'
        displayName: 'Build and Publish Docker Image'
        steps:
          - template: 'cicd/templates/dockerize.yml'